# Generated by Django 5.0.4 on 2024-05-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
                ('school_phone', models.CharField(max_length=15)),
                ('school_address', models.CharField(max_length=255)),
                ('school_contact', models.CharField(max_length=100)),
                ('school_contact_person', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
