# Generated by Django 5.0.4 on 2024-05-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolManagement',
            fields=[
                ('schoolMgtID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
    ]
