# Generated by Django 5.0.4 on 2024-05-06 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_schoolmanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolManagementSchools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.school')),
                ('schoolmanagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.schoolmanagement')),
            ],
        ),
    ]
